# Generated by Django 2.1.7 on 2019-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('FA', 'Farsi')], default='EN', max_length=10),
        ),
    ]
