# Generated by Django 2.1.5 on 2019-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190218_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_provided', models.CharField(blank=True, choices=[('h', 'hair styling'), ('n', 'nail styling'), ('m', 'makeup styling')], help_text='select the services you would like to provide', max_length=1)),
            ],
        ),
    ]
