# Generated by Django 2.1.5 on 2019-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='services',
            field=models.ManyToManyField(to='catalog.Services'),
        ),
    ]
